seed: 42
model:
  image_encoder: "microsoft/resnet-50"
  text_encoder: "facebook/opt-1.3b"
  frozen_image_encoder: false
  frozen_text_encoder: true
  pretrained_text_encoder: true
  num_image_tokens: 2

dataset:
  name: COCO
  path: "~/data/coco"

optimizer:
  algorithm: 'Adam'
  params:
    lr: 0.0003
    betas: [0.9, 0.95]
  
trainer:
  gpus: 1
  max_epochs: 40
  precision: 16
  gradient_clip_val: 1.0
  val_check_interval: 1.00
  resume_from_checkpoint: null

# data loader
loader:
  batch_size: 16
  pin_memory: false
  num_workers: 5

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/frozen

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_loss"
  mode: "min"

# resume training
checkpoint_path: null

# hydra-specific
hydra:
  run:
    dir: .

defaults:
  - override hydra/job_logging: disabled